language: python
python:
 - "3.4"
 - "3.5"
 - "3.6-dev"
 - "nightly"

matrix:
  allow_failures:
  - python: "nightly"

install:
 - "python setup.py install"

script:
 - "python examples/examples.py"
 - "nosetests -v tests/"
